# Generated by Django 3.1.1 on 2020-10-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200928_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='descripcion',
            field=models.TextField(max_length=60),
        ),
    ]
